-- ZwT Probeplan — Konzert-/Werkliste-Daten Saison 2026
-- Automatisch aus dem von Rafi hochgeladenen Excel-Export des Google
-- Sheets "ZwT 2026 - Probeplan" (Tab "config") generiert, 06.09.2026.
-- Seit der Saison-Verwaltung (07.09.2026) explizit auf die Saison 2026
-- skaliert (per Unterabfrage aufgelöst, siehe db/migration-saisons.sql).
-- Anwenden NACH db/schema.sql, db/migration-werke.sql UND
-- db/migration-saisons.sql:
--   docker compose exec -T db sh -c 'psql -U "$POSTGRES_USER" -d "$POSTGRES_DB"' < ../db/seed-werke-2026.sql

BEGIN;

-- Musiker:innen (Kürzel + echter Name aus dem Sheet)
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('AA', 'Alessandro D''Amico', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('AL', 'Alexander Lonquich', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('CF', 'Carlos Ferreira', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('DU', 'Dmytro Udovychenko', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('EM', 'Edouard Mätzener', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('ER', 'Emilie Richter', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('JK', 'Johannes Krebs', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('MEW', 'Mary Ellen Woodside', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('PFB', 'Pau Fernandéz Benlloch', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('RR', 'Rafael Rosenfeld', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('SP', 'Shanti Perpellini', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('TH', 'Tak Him', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('VL', 'Victor Yuanhan Lu', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('YL', 'Yura Lee', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('MAB', 'Miho Attila és barátai', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('MEh', 'Michel Ehrenbaum', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;
INSERT INTO musiker (kuerzel, name, saison_id) VALUES ('LP', 'Leandro Pezzoli', (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (kuerzel, saison_id) DO UPDATE SET name = EXCLUDED.name;

-- Feste Ablaufpunkte (Werk-Vorlagen) mit Standard-Teilnehmern
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (1, 'Saaleinlass', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (2, 'Flügelstimmung', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 2 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEh']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (3, 'Dîner', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 3 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['AL','PFB','VL','DU','YL','JK','ER','CF','MEh']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (4, 'Musikerführung im Kloster', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (5, 'Musikeressen', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 5 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','EM','AA','RR','AL','PFB','VL','DU','YL','JK','ER','CF']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (6, 'Gottesdienst', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 6 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','ER']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (7, 'Rede', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 7 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['RR']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (8, 'Apero Freundeskonzert', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 8 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','EM','AA','RR','VL','ER']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (9, 'Abschlussrede und Bedankungen', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 9 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','EM','AA','RR','AL','PFB','VL','DU','YL','JK','ER','CF','MEh']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (10, 'Schlussapero', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (11, 'Anlieferung/Stimmung Flügel', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 11 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEh']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (14, 'Aufbau Technik, Licht', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 14 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['SP']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (15, 'Soundcheck Mikrofon', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (16, 'Aufbau Apero', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (17, 'Freundeskonzert Rede', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (18, 'Umbau Saal', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (19, 'Practising AL', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 19 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['AL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (20, 'Practising PFB', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 20 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['PFB']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (21, 'Practising VL', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 21 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['VL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (22, 'Apero bei Birgit Miller', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlagen (nummer, name, typ, dauer_minuten, saison_id) VALUES (23, 'Einführung Holliger', NULL, NULL, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, typ = EXCLUDED.typ, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werk_vorlage_musiker (werk_vorlage_id, musiker_id) SELECT wv.id, m.id FROM werk_vorlagen wv, musiker m WHERE wv.nummer = 23 AND wv.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['RR','PFB']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;

-- Konzerte + ihre Werke
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (0, '0| Freundeskonzert Do 19.00 Kgh', 43.0, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 1, 'Schumann 3 Fantasiestücke op. 11', 12.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 0 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 1 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['VL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 2, 'Ligeti Solo', 9.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 0 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 2 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['ER']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 3, 'Beethoven op. 135', 24.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 0 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 3 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','EM','AA','RR']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (100, '1| Eröffnungskonzert «Zeichen» Fr 17.30', 51, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 101, 'Beethoven op. 135', 24.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 100 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 101 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','EM','AA','RR']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 102, 'Schumann Piano Quartet', 27.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 100 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 102 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['AL','DU','YL','JK']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (200, '2| Abendkonzert «Spiele» Fr 19.30', 58, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 201, 'Kurtag from Jatekok', 20.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 200 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 201 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['PFB','VL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 202, 'Mozart Kegelstatt', 20.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 200 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 202 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['PFB','YL','CF']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 203, 'Schumann Kinderszenen', 18.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 200 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 203 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['AL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (300, '3| «Late Night» Fr 22.15', 60, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 301, 'Attila Mihó és barátai', 60.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 300 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (400, '4| Matinee Kloster «Dialoge» Sa 10.45', 57, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 401, 'Mozart Duo B-Dur', 20.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 400 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 401 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['DU','YL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 402, 'Ligeti Solosonate', 9.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 400 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 402 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['ER']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 403, 'Mozart StrQuintet D-Dur', 28.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 400 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 403 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','AA','DU','YL','ER']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (500, '5| «The Broken Column» Sat 15.15', 60, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 501, 'Webern op.11', 3.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 500 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 501 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['PFB','JK']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 502, 'Kurtag from SGM', 12.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 500 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 502 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['AA','YL','ER']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
-- ÜBERSPRUNGEN (nicht-numerischer Code, siehe PROGRESS.md "Offene Fragen"): 502a Kurtag from SGM Va/VC
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 503, 'Hefti «The Broken Column»', 15.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 500 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 503 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','EM','AA','RR']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 504, 'Clara Schumann Klaviertrio', 30.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 500 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 504 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['VL','DU','ER']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (600, '6|«Hommage à Robert Schumann» Sat 17.15', 57, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 601, 'Schumann Nachtstücke Op 23', 16.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 600 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 601 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['PFB']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 602, 'Schumann Märchenerzählungen', 15.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 600 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 602 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['AL','YL','CF']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 603, 'Kurtág Hommage à R. Sch.', 10.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 600 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 603 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['AA','PFB','CF']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 604, 'Brahms Variationen 4-Händig', 16.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 600 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 604 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['AL','VL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (700, '7| Abendkonzert «Aus tiefer Not» Sat 19.15', 71, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 701, 'Bach/Kurtag "Aus tiefer Not schrei...."', 4.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 700 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 701 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['PFB','VL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 702, 'Bartok Solosonate Vl', 27.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 700 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 702 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['DU']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 703, 'Schubert T&M', 40.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 700 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 703 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','EM','AA','RR']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (800, '8| Matinee «zu Asche» Sun 11.15', 82, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 801, 'Schumann 3 Romanzen op. 94', 12.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 800 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 801 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['VL','CF']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 802, 'Kurtág Officium breve', 13.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 800 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 802 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','EM','AA','RR']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 803, 'Schumann Adagio aus VlKonz', 6.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 800 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 803 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['VL','DU','ER']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 804, 'Holliger Romancendres', 22.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 800 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 804 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['RR','PFB']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 805, 'Schumann Klaviertrio g-moll', 29.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 800 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 805 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['PFB','DU','JK']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (900, '9| «All’ongherese» Sun 16.00', 55.5, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 901, 'Haydn Klaviertrio G-Dur Nr. 39', 14.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 900 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 901 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['AL','DU','JK']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 902, 'Kurtag In Nomine Va solo', 4.5, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 900 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 902 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['YL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 903, 'Veress Introduzione e Coda', 10.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 900 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 903 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['EM','JK','CF']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 904, 'Kodaly Duo', 27.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 900 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 904 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['RR','YL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO konzerte (nummer, name, dauer_minuten, saison_id) VALUES (1000, '10| Abschlusskonzert Sun 18.30', 77, (SELECT id FROM saisons WHERE jahr = 2026)) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 1001, 'Bach "Gottes Zeit"', 3.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 1000 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 1001 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['PFB','VL']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 1002, 'Schumann F-Dur Klaviertrio op. 80', 30.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 1000 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 1002 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['RR','AL','DU']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 1003, 'Brahms Sextett G-Dur', 40.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 1000 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 1003 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','EM','AA','RR','YL','JK']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;
INSERT INTO werke (konzert_id, nummer, name, dauer_minuten, saison_id) SELECT id, 1004, 'Zugabe Schubert Ungarische Melodie', 4.0, (SELECT id FROM saisons WHERE jahr = 2026) FROM konzerte WHERE nummer = 1000 AND saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT (nummer, saison_id) DO UPDATE SET name = EXCLUDED.name, dauer_minuten = EXCLUDED.dauer_minuten, konzert_id = EXCLUDED.konzert_id;
INSERT INTO werk_musiker (werk_id, musiker_id) SELECT w.id, m.id FROM werke w, musiker m WHERE w.nummer = 1004 AND w.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) AND m.kuerzel = ANY(ARRAY['MEW','EM','AA','RR','YL','JK']) AND m.saison_id = (SELECT id FROM saisons WHERE jahr = 2026) ON CONFLICT DO NOTHING;

COMMIT;
